# Generated by Django 5.2.4 on 2025-08-14 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(help_text='Description of the cash collection source', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='CashCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of cash collection')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount collected in currency', max_digits=10)),
                ('note', models.TextField(blank=True, help_text='Additional notes about the cash collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(help_text='User who received the cash', on_delete=django.db.models.deletion.CASCADE, related_name='received_cash_collections', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_collections', to='memotab.source')),
            ],
            options={
                'verbose_name': 'Cash Collection',
                'verbose_name_plural': 'Cash Collections',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'source'], name='memotab_cas_date_862776_idx'), models.Index(fields=['received_by', '-date'], name='memotab_cas_receive_c0a5cc_idx')],
            },
        ),
    ]
