[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 manage.py migrate && python3 manage.py createsuperuser --noinput && python3 manage.py collectstatic --noinput && gunicorn myproject.wsgi"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10