# Generated by Django 5.2.4 on 2025-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('MRN_CREATED', 'MRN Created'), ('BILLED', 'Billed')], default='PENDING', max_length=20),
        ),
    ]
