# Generated by Django 5.2.4 on 2025-07-24 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvia', '0002_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('MEETING', 'In-Person Meeting'), ('ORDER', 'Order Related'), ('COMPLAINT', 'Complaint/Issue'), ('INQUIRY', 'General Inquiry'), ('PAYMENT', 'Payment Related'), ('OTHER', 'Other')], max_length=20)),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('interaction_summary', models.TextField(help_text='Brief summary of the interaction')),
                ('detailed_notes', models.TextField(blank=True, help_text='Detailed notes about the interaction')),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative'), ('URGENT', 'Urgent')], default='NEUTRAL', max_length=20)),
                ('priority_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('reliability_score', models.PositiveSmallIntegerField(blank=True, help_text='Reliability in commitments (1-10)', null=True)),
                ('communication_clarity', models.PositiveSmallIntegerField(blank=True, help_text='How clearly they communicate (1-10)', null=True)),
                ('payment_punctuality', models.PositiveSmallIntegerField(blank=True, help_text='Payment timeliness (1-10)', null=True)),
                ('order_consistency', models.PositiveSmallIntegerField(blank=True, help_text='Consistency in order patterns (1-10)', null=True)),
                ('trust_level', models.PositiveSmallIntegerField(blank=True, help_text='Level of mutual trust (1-10)', null=True)),
                ('openness_to_feedback', models.PositiveSmallIntegerField(blank=True, help_text='Receptiveness to suggestions (1-10)', null=True)),
                ('cooperation_level', models.PositiveSmallIntegerField(blank=True, help_text='Willingness to cooperate (1-10)', null=True)),
                ('loyalty_tendency', models.PositiveSmallIntegerField(blank=True, help_text='Tendency to remain loyal (1-10)', null=True)),
                ('primary_motivations', models.TextField(blank=True, help_text="What truly drives this dealer's decisions")),
                ('business_challenges', models.TextField(blank=True, help_text='Key challenges they face in their business')),
                ('success_metrics', models.TextField(blank=True, help_text='How they measure success and what matters most')),
                ('concerns_expressed', models.TextField(blank=True, help_text="Specific concerns or worries they've shared")),
                ('aspirations_goals', models.TextField(blank=True, help_text='Their business aspirations and long-term goals')),
                ('preferred_communication_style', models.CharField(blank=True, help_text='How they prefer to communicate', max_length=200)),
                ('decision_making_process', models.TextField(blank=True, help_text='How they make business decisions and who influences them')),
                ('information_preferences', models.TextField(blank=True, help_text='What type of information they value most')),
                ('timing_preferences', models.TextField(blank=True, help_text='When and how they prefer to be contacted')),
                ('topics_discussed', models.JSONField(default=list, help_text='List of topics/keywords discussed')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('intuitive_assessment', models.TextField(blank=True, help_text='Final intuitive judgment after structured trait evaluation')),
                ('issue_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, help_text='Key outcome or next step', max_length=200)),
                ('understanding_gained', models.TextField(blank=True, help_text='New understanding gained about the dealer')),
                ('tags', models.JSONField(default=list, help_text='Custom tags for categorization and filtering')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='sylvia.dealer')),
                ('products_mentioned', models.ManyToManyField(blank=True, help_text='Products discussed in this interaction', to='sylvia.product')),
            ],
            options={
                'verbose_name': 'Dealer Context',
                'verbose_name_plural': 'Dealer Contexts',
                'ordering': ['-interaction_date'],
                'indexes': [models.Index(fields=['dealer', '-interaction_date'], name='sylvia_deal_dealer__180c1a_idx'), models.Index(fields=['interaction_type', '-interaction_date'], name='sylvia_deal_interac_5ed304_idx'), models.Index(fields=['sentiment', 'priority_level'], name='sylvia_deal_sentime_30d1e4_idx'), models.Index(fields=['follow_up_required', 'follow_up_date'], name='sylvia_deal_follow__d21ac3_idx'), models.Index(fields=['reliability_score', 'trust_level'], name='sylvia_deal_reliabi_58a62e_idx')],
            },
        ),
    ]
