# Generated by Django 5.2.4 on 2025-08-17 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvia', '0003_dealercontext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_UPDATED', 'Order Updated'), ('MRN_CREATED', 'MRN Created'), ('MRN_APPROVED', 'MRN Approved'), ('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('ORDER_CANCELLED', 'Order Cancelled'), ('IMAGE_UPLOADED', 'MRN Image Uploaded'), ('IMAGE_DELETED', 'MRN Image Deleted')], max_length=30),
        ),
        migrations.CreateModel(
            name='OrderMRNImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(help_text='Krutrim Storage URL for the image', max_length=500)),
                ('image_type', models.CharField(choices=[('MRN_PROOF', 'MRN Proof Document'), ('DELIVERY_RECEIPT', 'Delivery Receipt'), ('QUALITY_CHECK', 'Quality Check Photo'), ('OTHER', 'Other Documentation')], default='MRN_PROOF', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the image')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary MRN proof image')),
                ('storage_key', models.CharField(blank=True, help_text='Krutrim storage key/path', max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrn_images', to='sylvia.order')),
            ],
            options={
                'ordering': ['-upload_timestamp'],
                'indexes': [models.Index(fields=['order', '-upload_timestamp'], name='sylvia_orde_order_i_795c89_idx'), models.Index(fields=['image_type', 'is_primary'], name='sylvia_orde_image_t_b098c7_idx')],
            },
        ),
    ]
