# Generated by Django 5.2.4 on 2025-08-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sylvia', '0004_alter_auditlog_action_ordermrnimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
