# Generated by Django 5.2.4 on 2026-01-20 06:56

from django.db import migrations


def create_default_organization(apps, schema_editor):
    """Create default organization and assign all users to it"""
    Organization = apps.get_model('sylvia', 'Organization')
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('sylvia', 'UserProfile')

    # Create default organization
    default_org, created = Organization.objects.get_or_create(
        slug='default',
        defaults={
            'name': 'Default Organization',
            'is_active': True,
        }
    )

    # Create UserProfile for all existing users
    for user in User.objects.all():
        UserProfile.objects.get_or_create(
            user=user,
            defaults={'organization': default_org}
        )


def reverse_migration(apps, schema_editor):
    """Reverse the migration by deleting user profiles and default org"""
    Organization = apps.get_model('sylvia', 'Organization')
    UserProfile = apps.get_model('sylvia', 'UserProfile')

    # Delete all user profiles
    UserProfile.objects.all().delete()

    # Delete default organization
    Organization.objects.filter(slug='default').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sylvia', '0006_organization_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_default_organization, reverse_migration),
    ]
