# Generated by Django 5.2.4 on 2026-01-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sylvia', '0008_appsettings_organization_auditlog_organization_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appsettings',
            unique_together={('organization', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='dealer',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='depot',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='mrn',
            unique_together={('organization', 'mrn_number')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('organization', 'order_number')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('organization', 'truck_number')},
        ),
    ]
