# Generated by Django 5.2.4 on 2026-01-20 07:12

from django.db import migrations


def assign_to_default_org(apps, schema_editor):
    """Assign all existing data to the default organization"""

    # Get models
    Organization = apps.get_model('sylvia', 'Organization')

    # Get or create default organization
    default_org, created = Organization.objects.get_or_create(
        slug='default',
        defaults={
            'name': 'Default Organization',
            'is_active': True,
        }
    )

    # List of tenant models to update
    tenant_models = [
        'Depot',
        'Product',
        'Dealer',
        'Vehicle',
        'Order',
        'OrderItem',
        'MRN',
        'OrderMRNImage',
        'AuditLog',
        'AppSettings',
        'NotificationTemplate',
        'DealerContext',
    ]

    # Update all records without an organization
    for model_name in tenant_models:
        Model = apps.get_model('sylvia', model_name)
        updated_count = Model.objects.filter(organization__isnull=True).update(
            organization=default_org
        )
        if updated_count > 0:
            print(f"Assigned {updated_count} {model_name} records to default organization")


def reverse_migration(apps, schema_editor):
    """Reverse migration - set organization to NULL"""
    # Note: This is a destructive operation and should be used carefully
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sylvia', '0009_alter_appsettings_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_to_default_org, reverse_migration),
    ]
