# Generated by Django 5.2.4 on 2026-01-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sylvia', '0010_assign_existing_data_to_default_org'),
    ]

    operations = [
        # Make organization field non-nullable for all tenant models
        migrations.AlterField(
            model_name='appsettings',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='dealercontext',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='depot',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='mrn',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='ordermrnimage',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='organization',
            field=models.ForeignKey(
                help_text='Organization this record belongs to',
                on_delete=django.db.models.deletion.PROTECT,
                to='sylvia.organization'
            ),
        ),
    ]
