# Generated by Django 5.2.4 on 2026-01-20 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvia', '0011_make_organization_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['organization', 'is_active'], name='sylvia_deal_organiz_a99fec_idx'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['organization', 'name'], name='sylvia_deal_organiz_a887e4_idx'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['gstin'], name='sylvia_deal_gstin_d8e0c1_idx'),
        ),
        migrations.AddIndex(
            model_name='depot',
            index=models.Index(fields=['organization', 'is_active'], name='sylvia_depo_organiz_752f03_idx'),
        ),
        migrations.AddIndex(
            model_name='depot',
            index=models.Index(fields=['organization', 'name'], name='sylvia_depo_organiz_37ebbc_idx'),
        ),
        migrations.AddIndex(
            model_name='mrn',
            index=models.Index(fields=['organization', 'status', '-mrn_date'], name='sylvia_mrn_organiz_1934dc_idx'),
        ),
        migrations.AddIndex(
            model_name='mrn',
            index=models.Index(fields=['organization', 'mrn_number'], name='sylvia_mrn_organiz_fecd42_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'status', '-order_date'], name='sylvia_orde_organiz_1a875d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'dealer', '-order_date'], name='sylvia_orde_organiz_2a950e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'depot', '-order_date'], name='sylvia_orde_organiz_be266d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'order_number'], name='sylvia_orde_organiz_8365a8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['whatsapp_sent', 'status'], name='sylvia_orde_whatsap_1c6ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_active'], name='sylvia_prod_organiz_a63812_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'name'], name='sylvia_prod_organiz_d6d36e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['organization'], name='sylvia_user_organiz_72437c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'organization'], name='sylvia_user_user_id_696d57_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization', 'is_active'], name='sylvia_vehi_organiz_76891d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization', 'truck_number'], name='sylvia_vehi_organiz_06dec7_idx'),
        ),
    ]
