# Generated by Django 5.2.4 on 2026-04-30 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylvia', '0013_organization_allowed_nav_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='advance_bill_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='block_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealer',
            name='risk_flag',
            field=models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='dealer',
            name='risk_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_UPDATED', 'Order Updated'), ('MRN_CREATED', 'MRN Created'), ('MRN_APPROVED', 'MRN Approved'), ('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('ORDER_CANCELLED', 'Order Cancelled'), ('IMAGE_UPLOADED', 'MRN Image Uploaded'), ('IMAGE_DELETED', 'MRN Image Deleted'), ('DEALER_BLOCKED', 'Dealer Blocked'), ('DEALER_UNBLOCKED', 'Dealer Unblocked'), ('DEALER_RISK_FLAGGED', 'Dealer Risk Flagged'), ('DEALER_RISK_CLEARED', 'Dealer Risk Cleared')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['organization', 'is_blocked'], name='sylvia_deal_organiz_e1ef03_idx'),
        ),
        migrations.AddIndex(
            model_name='dealer',
            index=models.Index(fields=['organization', 'risk_flag'], name='sylvia_deal_organiz_40c879_idx'),
        ),
    ]
