# Generated by Django 5.2.4 on 2025-08-27 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0001_initial'),
        ('sylvia', '0005_delete_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crossoverrecord',
            options={'ordering': ['-approved_date'], 'verbose_name': 'Crossover Record', 'verbose_name_plural': 'Crossover Records'},
        ),
        migrations.RemoveIndex(
            model_name='crossoverrecord',
            name='godown_cros_status_a3fb54_idx',
        ),
        migrations.RemoveIndex(
            model_name='crossoverrecord',
            name='godown_cros_destina_a8388c_idx',
        ),
        migrations.RemoveField(
            model_name='crossoverrecord',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='crossoverrecord',
            name='destination_vehicle',
        ),
        migrations.RemoveField(
            model_name='crossoverrecord',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='crossoverrecord',
            name='source_vehicle',
        ),
        migrations.RemoveField(
            model_name='crossoverrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='crossoverrecord',
            name='transfer_completion_time',
        ),
        migrations.RemoveField(
            model_name='crossoverrecord',
            name='transfer_start_time',
        ),
        migrations.RemoveField(
            model_name='crossoverrecord',
            name='transferred_damaged_bags',
        ),
        migrations.RemoveField(
            model_name='crossoverrecord',
            name='transferred_good_bags',
        ),
        migrations.AddIndex(
            model_name='crossoverrecord',
            index=models.Index(fields=['destination_dealer'], name='godown_cros_destina_6768e3_idx'),
        ),
    ]
