# Generated by Django 5.2.4 on 2025-08-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0002_alter_crossoverrecord_options_and_more'),
        ('sylvia', '0005_delete_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderintransit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_in_transit_product', to='sylvia.product'),
        ),
    ]
