# Generated by Django 5.2.4 on 2025-08-28 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0003_orderintransit_product'),
        ('sylvia', '0005_delete_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadingrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loading Records', 'verbose_name_plural': 'Loading Records'},
        ),
        migrations.RemoveIndex(
            model_name='loadingrequest',
            name='godown_load_status_393c8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='loadingrequest',
            name='godown_load_dealer__e23e82_idx',
        ),
        migrations.RemoveIndex(
            model_name='loadingrequest',
            name='godown_load_godown__3387c9_idx',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='allocated_bags',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='loading_completion_time',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='loading_start_time',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='required_by_date',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='loadingrequest',
            name='vehicle',
        ),
        migrations.AddIndex(
            model_name='loadingrequest',
            index=models.Index(fields=['dealer'], name='godown_load_dealer__0e77c4_idx'),
        ),
        migrations.AddIndex(
            model_name='loadingrequest',
            index=models.Index(fields=['godown'], name='godown_load_godown__9598f1_idx'),
        ),
    ]
