# Generated by Django 5.2.4 on 2025-08-29 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0005_godowndailybalance_godowninventoryledger_and_more'),
        ('sylvia', '0005_delete_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossoverrecord',
            name='destination_dealer',
            field=models.ForeignKey(blank=True, help_text='Dealer receiving the crossover goods', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crossover_deliveries', to='sylvia.dealer'),
        ),
    ]
