# Generated by Django 5.2.4 on 2025-08-29 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0006_alter_crossoverrecord_destination_dealer'),
        ('sylvia', '0005_delete_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderintransit',
            name='crossover_dealer',
            field=models.ForeignKey(blank=True, help_text='Dealer who will receive the crossover goods', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_crossovers', to='sylvia.dealer'),
        ),
    ]
