# Generated by Django 5.2.4 on 2025-10-15 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0007_orderintransit_crossover_dealer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(help_text='Krutrim Storage URL for the image', max_length=500)),
                ('image_type', models.CharField(choices=[('LOADING_PROOF', 'Loading Proof Document'), ('TRUCK_PHOTO', 'Truck/Vehicle Photo'), ('QUALITY_CHECK', 'Quality Check Photo'), ('BAG_COUNT', 'Bag Count Verification'), ('OTHER', 'Other Documentation')], default='LOADING_PROOF', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the image')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary loading proof image')),
                ('storage_key', models.CharField(blank=True, help_text='Krutrim storage key/path', max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('loading_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_images', to='godown.loadingrequest')),
            ],
            options={
                'verbose_name': 'Loading Request Image',
                'verbose_name_plural': 'Loading Request Images',
                'ordering': ['-upload_timestamp'],
                'indexes': [models.Index(fields=['loading_request', '-upload_timestamp'], name='godown_load_loading_ad002b_idx'), models.Index(fields=['image_type', 'is_primary'], name='godown_load_image_t_d27a37_idx')],
            },
        ),
    ]
