# Generated by Django 5.2.11 on 2026-02-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0012_org_scoped_unique_constraints'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='challanitembatchmapping',
            name='godown_cibm_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='crossoverrecord',
            name='godown_xover_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliverychallan',
            name='godown_dc_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliverychallanitem',
            name='godown_dci_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='godowndailybalance',
            name='godown_dbal_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='godowninventory',
            name='godown_inv_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='godowninventoryledger',
            name='godown_led_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='godownlocation',
            name='godown_godo_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryvariance',
            name='godown_ivar_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='ledgerbatchmapping',
            name='godown_lbm_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='loadingrequest',
            name='godown_lr_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='loadingrequestimage',
            name='godown_lrimg_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationlog',
            name='godown_nlog_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationrecipient',
            name='godown_nrec_organiz_crat_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderintransit',
            name='godown_orde_organiz_crat_idx',
        ),
    ]
